name: Build and Deploy

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Determine branch name
        id: branch_name
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk -F'/' '{print $3}')"

      - name: Pull current branch and push built files to it
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin ${{ steps.branch_name.outputs.branch }}  # Pull the latest changes from the current branch
          git add dist/
          git commit -m "Build and deploy dist files" || echo "No changes to commit"  # Commit if there are changes
          git push origin HEAD:${{ steps.branch_name.outputs.branch }}

      - name: Commit and push src and dist to master
        if: ${{ github.ref != 'refs/heads/master' }}  # Only run if not already on master
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git checkout master
          git pull origin master  # Pull the latest master branch
          git merge ${{ steps.branch_name.outputs.branch }}  # Merge the changes from the branch to master
          git add src/ dist/
          git commit -m "Merge src and dist from ${{ steps.branch_name.outputs.branch }}" || echo "No changes to commit"
          git push origin master