name: Build and Deploy

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Determine branch name
        id: branch_name
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk -F'/' '{print $3}')"

      - name: Commit and push built files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build and deploy dist files"
          git push origin HEAD:${{ steps.branch_name.outputs.branch }}
