name: Update Dist Branch

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "source" ]

jobs:
  update-dist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Push dist and package.json
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Store current branch name
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        
        # Create dist branch if it doesn't exist
        if ! git show-ref --quiet refs/remotes/origin/dist; then
          git checkout --orphan dist
          git rm -rf .
          git clean -fdx
        else
          git checkout dist || git checkout -b dist
        fi
        
        # Copy dist folder and package.json from current branch
        git checkout $CURRENT_BRANCH -- dist/ package.json
        
        # Check if there are any changes
        if git status --porcelain | grep .; then
          git add dist package.json -f
          git commit -m "chore: update dist folder and package.json [skip ci]"
          git push origin dist --force
        else
          echo "No changes to commit"
        fi