name: Build and Update Dist Branch

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-dist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm i
      
    - name: Clean dist
      run: rm -rf dist
        
    - name: Build
      run: npm run build
      
    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git config --local core.ignorecase false
    
    - name: Create and Update Dist Branch
      run: |
        # Create a new orphan branch (no history) if dist doesn't exist
        if ! git show-ref --verify --quiet refs/remotes/origin/dist; then
          git checkout --orphan dist
          git rm -rf .
          git clean -fdx
        else
          git fetch origin dist
          git checkout dist || git checkout -b dist origin/dist
        fi
        
        # Copy only dist folder and package.json from main branch
        git checkout main -- dist/ package.json || git checkout origin/main -- dist/ package.json
        
        # Stage all changes
        git add dist/ package.json
        
        # Commit and push if there are changes
        if git status --porcelain | grep .; then
          git commit -m "chore: update dist files"
          git push origin dist
        else
          echo "No changes to commit"
        fi