name: Update Dist Branch

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  update-dist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Push dist folder to dist branch
      run: |
        # Fetch dist branch
        git fetch origin dist
        
        # Switch to dist branch (will create tracking branch)
        git checkout dist
        
        # Remove old contents except .git
        git rm -rf .
        
        # Copy new dist contents
        cp -r dist/* .
        rm -rf dist
        
        # Commit and push changes
        git add .
        git commit -m "chore: update dist files [skip ci]"
        git push origin dist