name: Update Dist Branch

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  update-dist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Create dist branch if not exists
      run: |
        git ls-remote --heads origin dist | grep -q dist || git push origin `git rev-parse --short HEAD`:refs/heads/dist

    - name: Push dist and package.json
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Create dist branch if it doesn't exist
        git fetch origin dist:dist --depth=1 || true
        git checkout dist || git checkout --orphan dist
        
        # Remove existing files before copying
        rm -rf * ./*
        
        # Copy dist folder and package.json from source branch
        git checkout "$GITHUB_SHA" -- dist/ package.json || true
        
        # Stage and commit
        git add dist package.json -f
        git commit -m "chore: update dist folder and package.json [skip ci]"
        
        # Push to dist branch
        git push origin dist --force